(function(){ovi.provide("nokia.maps.util.ColorHelper");
(function(e){function k(a){var b;if(a.charAt(0)==="#")b=f[a.length]?a:null;else if(a.substr(0,3)==="rgb"){b=a.match(/\d+(\.\d+)?/g);var c=b.length;b=c>2&&c<5?["#",d(+b[0]),d(+b[1]),d(+b[2]),c>3?d(+b[3]*255):"ff"].join(""):null}b||e.d("Invalid color definition: "+a);return b}function h(a){return!/^(#|rgb).*/.test(a)}function d(a){return a<16?"0"+g(a).toString(16):g(a).toString(16)}function c(a){a=b(a,16);return(a<<4)+a}var g=Math.round,b=parseInt,f={4:function(a){return["#",a.charAt(1),a.charAt(1),
a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),"ff"].join("")},5:function(a){return["#",a.charAt(1),a.charAt(1),a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),a.charAt(4),a.charAt(4)].join("")},7:function(a){return a+"ff"},9:function(a){return a}},q={4:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),255]},5:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),c(a.charAt(4))]},7:function(a){a=b(a.substring(1),16);return[a>>16&255,a>>8&255,a&255,255]},9:function(a){a=b(a.substring(1),
16);return[a>>24&255,a>>16&255,a>>8&255,a&255]}};e.ColorHelper={toInternal:function(a){return h(a)?a:(a=k(a),f[a.length]?f[a.length](a):a)},toRGBA:function(a,b){return h(a)?[0,0,0,255]:(b||(a=k(a)),q[a.length](a))},getHex3:function(a,b){return h(a)?a:(b||(a=k(a),a=f[a.length]?f[a.length](a):a),a.substr(0,7))},getAlpha:function(a,c){return h(a)?1:(c||(a=k(a),a=f[a.length]?f[a.length](a):a),b(a.substr(7,2),16)/255)},toRandomRGBA:function(a,b){if(h(a))return"000000ff";else{for(var a=this.toRGBA(a,b),
c=0;c<4;c++)a[c]=""+d(c<3?Math.floor(Math.random()*(a[c]-0+1))+0:a[c]);return a.join("")}}}})(nokia.maps.util);ovi.provide("nokia.maps.util.Cache");
(function(e){function k(a,b,c,f){this.c=a;this.H=b;if(this.f!==f)this.f=f;if(c)(c.Y=this).W=c}function h(a,c){b.H=a;b.f=c===void 0?1:c;return b}function d(a){return a===void 0?1:isNaN(a=+a)||a<0||a===q?e.d():a}var c={},g={},b={},f={},q=1/0;e.Cache=new ovi.Class({initialize:function(a,b,c,f){this.Tb=d(a);if(b)this.Pd=b;if(c)this.we=c;if(f)this.X=f;this.q={}},Statics:{DONT:c,NEXT:g,NOT_ENOUGH_SPACE:f,change:h},f:0,change:h,add:function(a,e,l){var m=this.Pd,p=this.X,h=this.q,q=h[a],v;if(m){if((m=m(e))===
g)return q&&this.remove(a,1),p?p.add(a,e,l):g;if(m===c)return q&&this.remove(a),c;m===b?(e=m.H,l=m.f):e=m}if((l=d(l))>this.Tb)return p?p.add(a,e,l):f;if(q)this.f+=l-q.f,q.H=e,q.f=l,this.Ub(q);else{q=h[a]=this.V=new k(a,e,this.V,l);if(!this.fa)this.fa=q;this.f+=l}for(;this.f>this.Tb;)this.R((v=this.fa).c,v),p&&p.add(v.c,v.H,v.f)},get:function(a,b){var c=this.q[a],f;c&&(b||this.Ub(c));return c?c.H:(f=this.X)?f.get(a,b):void 0},remove:function(a,b){var c=this.q[a],f,d;c&&this.R(a,c);if(!b&&(f=this.X))d=
f.remove(a,b);return c?c.H:d},removeAll:function(a){var b=this.q,c,f;for(c in b)b.hasOwnProperty(c)&&!c.indexOf(a)&&this.R(c,b[c]);(f=this.X)&&f.removeAll(a)},destroy:function(){var a=this.q,b,c;for(c in a)(b=a[c]).W=0,b.Y=0;this.fa=this.V=0;this.X&&this.X.destroy()},R:function(a,b,c){var f=b.Y,d=b.W,g;f?d?(f.W=d).Y=f:(this.fa=f).W=void 0:(this.V=d)?d.Y=void 0:this.fa=void 0;if(!c)delete this.q[a],this.f-=b.f,(g=this.we)&&g(b.H);return b.H},Ub:function(a){var b=this.V;if((b=this.V)!==a){this.R(a.c,
a,1);if(b)(b.Y=a).W=b;(this.V=a).Y=void 0}}});k.prototype.f=1})(nokia.maps.util);ovi.provide("nokia.maps.map.provider.IData");ovi.provide("nokia.maps.map.provider.IObjectProvider");ovi.provide("nokia.maps.util.proto");
(function(){var e={}.toString,k=nokia.maps.util.proto=function(h,d,c,g){var b=Function(),f,q;b.prototype=d;b=new b;for(f in h)h.hasOwnProperty(f)&&(b[f]=c&&f in d&&e.call(q=h[f])==="[object Object]"?k(q,d[f],c):h[f]);if(c&&!g)for(f in d)if(d.hasOwnProperty(f)&&(q=d[f])===b[f]&&e.call(q)==="[object Object]")b[f]=k(0,q,c);return b}})();ovi.provide("nokia.maps.map.component.zoom.MouseWheel");
(function(e){var k={1:Math.floor,"-1":Math.ceil};e.map.component.zoom.MouseWheel=new ovi.Class({Extends:e.map.component.Component,c:"zoom.MouseWheel",n:"0.0.0.1",initialize:function(){this.dd=ovi.bind(this,this.dd);this.s=this.MAP_2D|this.GLOBE|this.PANORAMA;this._super({enabled:!0})},dd:function(e){var d=e.display,c=d.baseMapType.pType,g=e.timeStamp,b,f;if(this.enabled){b=e.deltaY<0?-1:1;if(c===this.PANORAMA)c=d.getCam(),c.fov+=b,d.setCam(c);else if(g-this.Oh>=200)this.Oh=g,c=d.getZoom(g=e.displayX,
f=e.displayY),d.setZoomLevel(e.shiftKey?c-b/20:k[b](c-b),"default",g,f);e.cancel()}},Oh:0,attach:function(e){this._super(e);e.addListener("wheel",this.dd)},detach:function(e){this._super(e);e.removeListener("wheel",this.dd)}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleClick");
(function(e){var k=e.map.component;k.zoom.DoubleClick=new ovi.Class({Extends:k.Component,c:"zoom.DoubleClick",n:"0.0.0.1",initialize:function(){function e(b){var a=g.getZoom(b.displayX,b.displayY);if(c.enabled){var d=b.button===2;(f=g.getComponentById("panning.Kinetic"))&&f.set("current",null);g.setZoomLevel(Math[d?"floor":"ceil"](a+(d?-1:1)),"default",b.displayX,b.displayY)}}function d(b){c.enabled&&b.preventDefault()}var c=this,g,b=k.Component.prototype,f;c.s=c.MAP_2D|c.GLOBE;c._super({enabled:!0});
c.attach=function(f){b.attach.call(c,f);g=f;g.addListener("dblclick",e);g.addListener("contextmenu",d)};c.detach=function(f){b.detach.call(c,f);g.removeListener("dblclick",e);g.removeListener("contextmenu",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleTap");
(function(e){var k=e.map.component;k.zoom.DoubleTap=new ovi.Class({Extends:k.Component,c:"zoom.DoubleTap",n:"0.0.0.1",initialize:function(){function e(b){var h=c.getZoom(b.displayX,b.displayY);d.enabled&&((g=c.getComponentById("panning.Kinetic"))&&g.set("current",null),c.pixelToGeo(b.displayX,b.displayY),c.setZoomLevel(h+1,"default",b.displayX,b.displayY),b.cancel())}var d=this,c,g,b=k.Component.prototype;d.s=d.MAP_2D;d._super({enabled:!0});d.attach=function(f){b.attach.call(d,f);c=f;c.addListener("dbltap",
e)};d.detach=function(f){b.detach.call(d,f);c.removeListener("dbltap",e)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.GestureEvent");
(function(e){var e=e.map.component,k,h,d=ovi.Array.forEach,c=ovi.Array.indexOf,g=e.Component.prototype,b=["gesturestart","gestureend","gesturechange","touchstart","touchmove","touchend"];e.zoom.GestureEvent=new ovi.Class({Extends:e.Component,c:"zoom.GestureEvent",n:"0.0.0.1",initialize:function(){h=this;h.s=h.MAP_2D;h._super();h.attach=function(c){g.attach.call(h,c);k=c;d(b,function(b){k.addEvent(b)})};h.detach=function(c){g.detach.call(h,c);d(b,function(b){k.removeEvent(b)})}},addListener:function(f,
d){if(c(b,f)>=0)return k.addListener(f,d),!0;return!1},removeListener:function(f,d){if(c(b,f)>=0)return k.removeListener(f,d),!0;return!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Click");
(function(e){var k=e.map.component;k.panning.Click=new ovi.Class({Extends:k.Component,c:"panning.Click",n:"0.0.0.1",initialize:function(e){function d(f){c.enabled&&b.setCenter(b.pixelToGeo(f.targetX,f.targetY),"default")}var c=this,g=k.Component.prototype,b;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("click",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("click",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Tap");
(function(e){var k=e.map.component;k.panning.Tap=new ovi.Class({Extends:k.Component,c:"panning.Tap",n:"0.0.0.1",initialize:function(e){function d(f){c.enabled&&b.setCenter(b.pixelToGeo(f.targetX,f.targetY),"default")}var c=this,g=k.Component.prototype,b;c.s=c.MAP_2D;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("tap",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("tap",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.HitArea");
(function(){var e=Math,k=e.PI/180,h=e.ceil,d=e.min,c=e.sin,g=e.cos,b=nokia.maps.util,f=b.Point,q=nokia.maps.map.HitArea=new ovi.Class({initialize:function(a,f){var e=(f=[].concat(f)).length,m=e,p,q,s,v,u;this.values=f;for(this.type=a;m--;)isNaN(f[m]=f[m])&&b.d("Given argument is not the array of numbers");a==="rect"&&e>3&&(f=[+f[0],+f[1],+f[2],+f[1],+f[2],+f[3],+f[0],+f[3]],a="poly");if(a==="circle"&&e>2&&(s=+f[2])>0){p=+f[0];q=+f[1];m=d(h(s)*2,40);v=360/m;for(f=[];m--;)u=v*m*k,f.push(p+c(u)*s,q+
g(u)*s);a="poly"}if(a==="poly"&&e&&!(f.length%2))this.Zb=f;!this.Zb&&b.d("bad polygon")},Statics:{from:function(a){return a instanceof q?a:new q(a.type,a.values?a.values:a.coords)}},hitTest:function(a,b,c){return f.isCoveredBy(a,b,this.Zb,c,!0)}})})();ovi.provide("nokia.maps.map.provider.NullObjectProvider");
(function(e){e.map.provider.NullObjectProvider=new ovi.Class({cg:function(){},Wh:function(){},rc:function(){},requestBBox:function(){return[]},cancelBBoxRequest:function(){},adopt:function(e){if(e.e)return!1;e.e=this;return e},orphan:function(e){if(e.e!==this)return!1;e.e=null;return e}})})(nokia.maps);ovi.provide("nokia.maps.map.render.Capabilities");
(function(){if(!nokia.maps.util.getConstructor(nokia.maps.map.render.Capabilities))var e=nokia.maps,k={min:0,max:0},h=(e.map.render.Capabilities=function(d){return e.util.proto(d,h,!0,!0)}).prototype={view:{heading:k,tilt:k,incline:k,distance:k,zoom:{min:-1/0,max:1/0}},cam:{fov:{min:70,max:70}},altMode:{GL:!0,OL:!1,SL:!1,SB:!1,WE:!1,WG:!1},provider:{tile:{bmp:!0,gfx:!1,mesh:!1},object:{spatial:!0,marker:!0,decal:!1}},ui:17,capture:!1,ZOOM:1,HEADING:2,TILT:4,INCLINE:8,COORD:16,FOV:32,SIZE:64}})();
ovi.provide("nokia.maps.map.component.panning.Kinetic");(function(e){var k=e.map.component,h=k.panning;if(!e.util.getConstructor(h.Kinetic))h.Kinetic=new ovi.Class({Extends:k.Component,c:"panning.Kinetic",n:"0.0.0.1",initialize:function(d){this._super(ovi.extend({current:null},d))},attach:function(d){this._super(d);d.bh=!0},detach:function(d){this._super(d);d.bh=!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.panorama.Click");
(function(e){var k=e.map.component;k.panning.panorama.Click=new ovi.Class({Extends:k.Component,c:"panning.panorama.Click",n:"0.0.0.1",initialize:function(e){function d(f){c.enabled&&f.button===0&&b.setView(b.m.viewForXY(f.targetX,f.targetY),"default")}var c=this,g=k.Component.prototype,b;c.s=c.PANORAMA;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("click",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("click",d)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.zoom.Gesture");
(function(e){var k=e.map.component;k.zoom.Gesture=new ovi.Class({Extends:k.Component,c:"zoom.Gesture",n:"0.0.0.1",initialize:function(){this.s=this.MAP_2D;this.onGestureStart=ovi.bind(this,this.onGestureStart);this.onGestureEnd=ovi.bind(this,this.onGestureEnd);this.onTouch=ovi.bind(this,this.onTouch);this._super({enabled:!0})},Mc:!1,Sc:!1,onGestureStart:function(e){if(this.enabled)this.Mc=!0,e.preventDefault()},onGestureEnd:function(e){if(this.enabled)this.Sc=this.Mc=!1,this.mapDisplay.m.endInteraction(),
e.preventDefault()},onTouch:function(e){if(this.enabled&&this.Mc){var d=this.mapDisplay.m,c=e.touches,g=c.length>1,e=e.timeStamp,b=c[0].pageX,f=c[0].pageY,k=g?c[1].pageX:void 0,c=g?c[1].pageY:void 0;this.Sc?d.interact(e,b,f,k,c):(d.beginInteraction(d.capabilities.ZOOM|d.capabilities.COORD,null,e,b,f,k,c),this.Sc=!0)}},attach:function(e){var d;this._super(this,e);this.mapDisplay=e;this.Xg=d=new k.zoom.GestureEvent;e.addComponent(d);d.addListener("gesturestart",this.onGestureStart);d.addListener("gestureend",
this.onGestureEnd);d.addListener("touchstart",this.onTouch);d.addListener("touchmove",this.onTouch)},detach:function(e){var d=this.Xg;this._super(this,e);this.mapDispay=null;e.removeComponent(d);d.removeListener("gesturestart",this.onGestureStart);d.removeListener("gestureend",this.onGestureEnd);d.removeListener("touchstart",this.onTouch);d.removeListener("touchmove",this.onTouch);this.Xg=null;this.Sc=this.Mc=!1},enableRotation:function(){},disableRotation:function(){this.kv=!1},enableZoom:function(){this.xo=
!0},disableZoom:function(){this.xo=!1}})})(nokia.maps);ovi.provide("nokia.maps.map.Object");
(function(e){if(!e.util.getConstructor(e.map.Object)){var k=0,h=0,d=function(c,b){var f=c.Oa(),d=b.Oa(),a,e,l,m=0,p;if(!f||!d)return 0;a=f.length;e=d.length;for(l=a<e?a:e;m<l;m++)if(p=d[m]-f[m])return h?-p:p;return h?a-e:e-a},c={rev:0,sort:function(c,b,f){var e=[],a,r,l=c.length;for(r=0;r<l;r++)((a=c[r]).getIconForRendering||a.drawToTile)&&(b||a.isVisible())&&e.push(a);h=f;e.sort(d);return e},create:function(c){var b=c.t,f;f=null;b&&(f=(f=b.Oa())?f.slice():[],f.push(c.zIndex,b.objects.indexOf(c)));
return f}};nokia.maps.map.Object=new ovi.Class({Extends:e.util.OObject,Mixins:e.dom.EventTarget,Statics:{sortByZInfo:c.sort,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4},dispatch:function(c){c.display=this.getDisplay();return e.dom.EventTarget.prototype.dispatch.call(this,c)},initialize:function(c){this.e=new e.map.provider.NullObjectProvider;this.id=k++;c&&"draggable"in c?(c.isDraggable=c.draggable,delete c.draggable,this._super(c),c.draggable=c.isDraggable,delete c.isDraggable):this._super(c);
this.addObserver("*",this.ac,this)},t:null,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4,isEventTarget:!0,zIndex:0,visibility:!0,u:"object",Nc:function(){return this.Ob||(this.Ob={})},destroy:function(){var c=this.t;c&&c.objects.remove(this);this.removeAllListeners();this.e=null;this.removeObserver("*",this.ac,this)},getInvalidations:function(c){var b=this.Ob;return b?(b[1]>c)*1|(b[2]>c)*2|(b[4]>c)*4:0},ac:function(c,b){this.ia(b,0)},getProvider:function(){return this.e},getParent:function(){return this.t},
getRoot:function(){for(var c=this,b;b=c.t;)c=b;return c},getDisplay:function(){var c=this.getRoot();return c.u==="display"?c:null},isVisible:function(){var c=this,b=!1;do b=c.visibility;while(b&&(c=c.t));return b},ia:function(c,b){var f;f=this.e;var d;b|=c==="zIndex"?4:c==="visibility"?2:0;d=f.rc(this,b);f=this.Nc();b&1&&(f[1]=d);b&2&&(f[2]=d);b&4&&(f[4]=d)},zIndexSetter:function(c){this.Pb();return c},eventListenerSetter:function(c){var b=0,f,d;if(c)for(d in this.removeAllListeners(),c)if((b=ovi.type(f=
c[d]))==="array")for(b=0;b<f.length;b+=3)this.addListenerNS(f[b+2],d,f[b],f[b+1]);else b==="function"&&this.addListenerNS(null,d,f,!1)},Oa:function(){var d;if(!(d=this.pc))d=this.pc=c.create(this);return d},Pb:function(){this.pc=void 0},adopt:function(c){return c.adopt(this)},orphan:function(){return this.e.orphan(this)}})}})(nokia.maps);ovi.provide("nokia.maps.map._MarkerIcon");
(function(){function e(c){return new b(typeof c==="object"?c.strokeColor?{strokeColor:a(c.strokeColor)}:void 0:{strokeColor:c})}var k=nokia.maps,h=k.map.HitArea,d=k.util,c=d.proto,g=d.Point,b=d.Pen,f=new b({strokeColor:"#FFF"}),q=d.Brush,a=d.ColorHelper.getHex3,r=k.gfx,l=r.GraphicsImage,m=r.IDL,p=r.Color.parseCss,z=[4207599104,4207599105,4207599106,"$Text$"],s=new k.gfx.SvgParser,v=d.$c("shape text textPen pen brush effect"),u=d.flatMerge(d.$c("anchor hitArea"),v),x=new d.Cache(50),w=nokia.maps.map.Hb=
new ovi.Class({Extends:nokia.maps.util.OObject,initialize:function(a){var b;a&&a.shape&&a.shape!==this.shape?(this.shape=this.shapeSetter(b=a.shape),delete a.shape,this._super(a),a.shape=b):(this.shapeSetter(this.shape),this._super(a));this.addObserver("*",this.ee)},Statics:{kn:u,Ta:function(a){return a in u},te:function(a){return!(a in v)},fc:{balloon:['<path style="opacity:0.4;fill:#353535" d="m 19,31 c 0,1.67 -2.69,3 -6,3 c -3.31,0 -6,-1.33 -6,-3 c 0,-1.67 2.69,-3 6,-3 c 3.31,0 6,1.33 6,3 z" /><path style="fill:#Facade01" d="m 13,0 c -3.47,0 -6.73,1.32 -9.19,3.75 C 1.36,7.82 0,9.41 0,12.84 c 0,3.43 1.36,6.64 3.81,9.06 L 13,31 l 9.19,-9.094 c 2.46,-2.43 3.81,-5.63 3.81,-9.06 c 0,-3.43 -1.36,-6.67 -3.81,-9.09 C 19.73,1.32 16.47,0 13,0 z"/><path style="fill:#ffffff" d="m 13,1 c -3.21,0 -6.23,1.23 -8.5,3.47 c -2.26,2.24 -3.5,5.22 -3.5,8.38 c 0,3.16 1.24,6.14 3.5,8.38 l 8.5,8.38 l 8.5,-8.38 c 2.26,-2.24 3.5,-5.22 3.5,-8.38 c 0,-3.16 -1.24,-6.14 -3.5,-8.38 C 19.23,2.23 16.2,1 13,1 z"/><path style="fill:#Facade00;fill-opacity:1" d="m 13,2.19 c -7,0 -10.74,4.96 -10.81,10.65 c 0,3.27 0.95,5.61 3.03,7.66 l 7.79,7.69 l 7.79,-7.69 c 2.07,-2.05 3.02,-4.27 3.03,-7.66 C 23.58,7.07 19.98,2.19 13,2.19 z"/><text x="13" y="18" font-size="10pt" font-family="arial" font-weight="bold" text-anchor="middle" fill="#Facade02">$Text$</text>',
28,36,13,31,"poly",[0,16,0,7,8,0,18,0,26,7,26,16,18,34,8,34]]}},text:"",pen:c({},f),textPen:c({},f),brush:c({},new q({color:"#1080DD"})),shape:"balloon",effect:"none",ee:function(a,b){if(b in v)a.c="",a.Pa=0},shapeSetter:function(a){var b=w.fc[a]||d.d("shape");this.f=new g(b[1],b[2]);this.anchor=new g(b[3],b[4]);this.hitArea=b[5]?new h(b[5],b[6]):void 0;return a},brushSetter:function(b){return new q(typeof b==="object"?b.color?{color:a(b.color)}:void 0:{color:b})},penSetter:e,textPenSetter:e,textSetter:function(a){return d.sanitizeText(a)},
be:function(){var a=w.fc[this.shape],b,c,f,d;if(a&&typeof a[0]==="string"){b=z.length;for(c=a[0]=ovi.Array(s.parseSvg('<svg version="1.1" width="'+(f=a[1])+'" height="'+(d=a[2])+'" viewBox="0 0 '+f+" "+d+'">'+a[0]+"</svg>").data);b--;){d=[];for(f=-1;(f=c.indexOf(z[b],f+1))!==-1;)d.push(f);d.length&&(a[7+b]=d)}}return a},Je:function(a){for(var b=[p(this.brush.color,1),p(this.pen.strokeColor,1),p(this.textPen.strokeColor,1),this.text],c=b.length,f=a[0].slice(),d,g;c--;)if(d=a[7+c])for(g=d.length;g--;)f[d[g]]=
b[c];return f},getIcon:function(){var a,b;if(!this.Pa){if(!(b=x.get(a=this.ea())))x.add(a,b=new l(new m(this.Je(this.be()))));this.Pa=b}return this.Pa},ea:function(){return this.c||(this.c=(this.hasOwnProperty("shape")?this.shape:"").concat(this.text,this.textPen.ea(),"P",this.pen.ea(),"B",this.brush.ea()))}})})();ovi.provide("nokia.maps.map.Marker");
(function(){var e=nokia.maps,k=e.util,h=e.dom,d=e.map,c=e.gfx,g=k.Point,b=k.Strip,f=new g(0,0),q=k.Rectangle,a=d.Hb,r=e.geo,l=d.HitArea,m=r.Coordinate,e=new ovi.Class({Extends:d.Object,initialize:function(b,c){var f;if(this.u==="marker"&&(!c||!("icon"in c)))f=new a,this.set("icon",f.getIcon()),this.set("anchor",f.anchor),this.set("hitArea",f.hitArea);this.Qa={};this._super(c);this.set("coordinate",b,1)},u:"marker",anchor:f,f:f,coordinateSetter:function(a){(a=m.fromObject(a))||k.d("coord");this.Qa=
{};return a},hitAreaSetter:function(a){return!a?a:l.from(a)},anchorSetter:function(a){(a=g.fromObject(a))||k.d("you have to set util.Point");return a},draggableSetter:function(a){return this.isDraggable=a},Ka:function(a){this.f=new g(a.width,a.height);this.gc=1},iconSetter:function(a){ovi.type(a);a instanceof c.Image||(a=c.Image.fromObject(a));a instanceof c.Image||k.d("icon");this.icon=a.C===document?a:a.clone(document);a.state===1?this.Ka(a):this.gc=0;return this.icon},getBoundingBox:function(){return r.BoundingBox.coverAll([this.coordinate])},
getDisplayBoundingBox:function(a){a=a.geoToPixel(this.coordinate).sub(this.anchor);return new q([a,a.add(this.f)])},hitTest:function(a,b,c,f){var a=this.getDisplayBoundingBox(a),d=new g(b,c),e=this.hitArea;return a.contains(d)&&(!e||e.hitTest(b-a.topLeft.x,c-a.topLeft.y,f))},getDisplayOffset:function(a,b,c){return(new g(b,c)).sub(a.geoToPixel(this.coordinate))},ia:function(a,b){a!=="zIndex"&&(b|=a==="coordinate"?1:2);this._super(a,b)},fe:function(a){var b="error";a.state===1&&(this.Ka(a),this.ia("icon",
2),b="load");this.dispatch(new h.Event({type:b,target:this,relatedTarget:a}))},getIconForRendering:function(a){var b=this.icon;a!==document&&(b=b.clone(a));b.state?this.gc||b.state===1&&this.Ka(b):b.prepare(this.fe,this);return b},project:function(a){return this.Qa[a.id]||(this.Qa[a.id]=a.geoToMapPoints(b.stencil(b.LAT_LNG,[this.coordinate.latitude,this.coordinate.longitude])))}});if(d.Marker.isNs)d.Marker=e})();ovi.provide("nokia.maps.map.StandardMarker");
(function(){function e(c,d,b){c.U.set(d,b);if(d==="shape")c.f=c.U.f,c.set("anchor",c.U.anchor),c.set("hitArea",c.U.hitArea);return c.U[d]}var k=nokia.maps,h=k.util,d=k.map.Hb,k=nokia.maps.map.StandardMarker=new ovi.Class({Extends:nokia.maps.map.Marker,initialize:function(c,g){var b=this.U=new d(h.flatMerge({},g,1,d.Ta));h.flatMerge(this,b,1,d.Ta);this.f=b.f;this._super(c,h.flatMerge({},g,1,d.te))},u:"standardmarker",shapeSetter:function(c){return e(this,"shape",c)},textSetter:function(c){return e(this,
"text",c)},textPenSetter:function(c){return e(this,"textPen",c)},penSetter:function(c){return e(this,"pen",c)},brushSetter:function(c){return e(this,"brush",c)},getIconForRendering:function(c){this.set("icon",this.U.getIcon());return this._super(c)}});h.flatMerge(k.prototype,d.prototype,!0,d.Ta)})();ovi.provide("nokia.maps.map.component.objects.DragMarker");
(function(e){var k=e.util.Point,e=e.map,h=e.component,d=e.Marker,c=d.prototype.u,g=e.StandardMarker.prototype.u;h.objects.DragMarker=new ovi.Class({Extends:h.Component,c:"objects.DragMarker",n:"0.0.0.1",dragSourceOpacity:1,dragIconOpacity:0.5,initialize:function(b){function f(a){var b=a.dataTransfer,f=b&&b.getData("application/map-drag-type"),e=b&&b.getData("application/map-drag-object");if((f===c||f===g)&&e instanceof d){if(e.t)b.dropEffect="none";else if(b.allows("move"))b.dropEffect="move";else{b.dropEffect=
"none";a.cancel();return}f=b.getData("application/map-drag-object-offset")||new k(0,0);e.set("coordinate",s.pixelToGeo(a.displayX-f.x+e.anchor.x,a.displayY-f.y+e.anchor.y));b.dropEffect!=="none"&&s.objects.add(e);a.cancel()}else b.dropEffect="none"}function e(a){var b=a.dataTransfer,f=b&&b.getData("application/map-drag-type"),d=b&&b.getData("application/map-drag-object");if(f===c||f===g)b.dropEffect=d.t?"move":"copy",a.cancel()}function a(a){var b=a.dataTransfer,f=b&&b.getData("application/map-drag-type"),
d=b&&b.getData("application/map-drag-object");if(f===c||f===g)b.dropEffect=d.t?"move":"copy",a.cancel()}function r(a){var b=(a=a.dataTransfer)&&a.getData("application/map-drag-type"),f=a&&a.getData("application/map-drag-object");a&&a.getData("application/map-drag-object-display");if(b===c||b===g){f.removeListener("dragend",r,!0);if(a.dropEffect==="move"&&!s.contains(f))dragMarkerParent=f.t,dragMarkerParent.objects.remove(f);f.icon.opacity=1;f.ia("icon",2)}}function l(a){var b=a.dataTransfer,b=b&&
b.getData("application/map-drag-type");(b===c||b===g)&&a.stopImmediatePropagation()}function m(a){if(p.enabled){var b,c,f,g=a.target,e=a.dataTransfer;if(g instanceof d&&g.isDraggable)c=g.getDisplayBoundingBox(s),b=a.displayX-c.topLeft.x,c=a.displayY-c.topLeft.y,f=g.getIconForRendering(document),e.setDragImage(f.createElement(p.dragIconOpacity),-b,-c),g.icon.opacity=p.dragSourceOpacity,g.ia("icon",2),e.setData("application/map-drag-type",g.u),e.setData("application/map-drag-object",g),e.setData("application/map-drag-object-offset",
new k(b,c)),e.effectAllowed="all",e.setData("application/map-drag-object-display",s),g.insertListener("dragend",r,!0),a.stopImmediatePropagation()}}var p=this,z=h.Component.prototype,s;p.s=p.MAP_2D|p.GLOBE;p._super(ovi.extend({enabled:!0,useKineticPanning:!0},b));p.attach=function(b){z.attach.call(p,b);s=b;s.addListener("dragstart",m);s.addListener("drag",l);s.addListener("dragend",r);s.addListener("dragenter",a);s.addListener("dragover",e,!0);s.addListener("drop",f)};p.detach=function(b){z.detach.call(p,
b);s.removeListener("dragstart",m);s.removeListener("drag",l);s.removeListener("dragend",r);s.removeListener("dragenter",a);s.removeListener("dragover",e);s.removeListener("drop",f)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Drag");
(function(e){function k(b){return 1*b.altKey+2*b.ctrlKey+4*b.metaKey+8*(b.button===2||b.button===0&&(b.shiftKey||h&&b.ctrlKey))}var h=e.dom.Page.platform.mac,d=e.map,c=d.component,g=new d.render.Capabilities,b={duration:function(){return 600},ease:e.util.animation.easeFunctions.LINEAR,power:function(){return 1}};c.panning.Drag=new ovi.Class({Extends:c.Component,c:"panning.Drag",n:"0.0.0.1",initialize:function(f){function d(b){l.enabled&&l.D&&(a(b),p.endInteraction(),p.setTransition(p.va.TRANSITION.AUTO))}
function a(a){var b=a.dataTransfer;if(l.enabled&&l.D&&b&&b.getData("application/map-drag-type")==="map"){var b=a.deltaX,c=a.deltaY;k(a)!==h?e(a):(b||c)&&p.interact(a.timeStamp,a.displayX,a.displayY)}}function e(c){var f;if(l.enabled&&l.D)f=c.dataTransfer,h=k(c),f.cursor=h&8?"move":"hand",f.lift=!1,f.setData("application/map-drag-type","map"),f.setData("application/map-drag-object",p),f.setData("application/map-drag-object-offset",void 0),p.setTransition(p.va.TRANSITION.NONE),p.beginInteraction(h&
8?g.HEADING|g.TILT:g.COORD,p.bh?b:"",c.timeStamp,c.displayX,c.displayY),a(c)}var l=this,m=c.Component.prototype,p,h;l.D=!0;l.s=l.PANORAMA|l.MAP_2D|l.GLOBE;l._super(ovi.extend({enabled:!0,useKineticPanning:!0},f));l.attach=function(b){m.attach.call(l,b);p=b;p.addListener("dragstart",e);p.addListener("drag",a);p.addListener("dragend",d)};l.detach=function(b){m.detach.call(l,b);p.removeListener("dragstart",e);p.removeListener("drag",a);p.removeListener("dragend",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.Behavior");
(function(e){var e=e.map.component,k=e.zoom,h=e.panning,d=new ovi.Array([e.objects.DragMarker,k.MouseWheel,k.DoubleClick,k.DoubleTap,k.Gesture,h.Drag,h.Kinetic,h.panorama.Click]);e.Behavior=new ovi.Class({Extends:e.Component,c:"Behavior",n:"0.0.0.1",s:this.PANORAMA|this.MAP_2D,initialize:function(){this.Qe=new ovi.Array},attach:function(c){d.forEach(function(d){d&&this.Qe.push(c.addComponent(new d))},this);this.mapDisplay=c},detach:function(){this.Qe.forEach(function(c){this.mapDisplay.removeComponent(c)},
this);this.Qe.length=0;delete this.mapDisplay}})})(nokia.maps);ovi.provide("nokia.maps.behavior._packaging.package-all");})();
